### ISSUE TITLE
Find the Number which contains the digit d

### ISSUE THREAD

**Issue by varchasa** [varchasa/code-for-hacktoberfest#9]
Take a user input n and d and prints numbers between 0 to n which contains specific digit d.

**Comment by KoushikSahu** [comment]
I want to work on this issue. Please assign it to me.

**Comment by DhawalKhapre** [comment]
Please assign this issue to me

**Comment by varchasa** [comment]
You both can work on this issue. No need of assigning just create a pull request and I will approve which has more optimised soluton and not a copied one.

**Comment by KoushikSahu** [comment]
@varchasa I have made a PR. Please review it and let me know if I need to modify or rectify anything.
